version: '3.7'

services:
    app:
        container_name: lv
        build: ./docker/local/php
        restart: always
        working_dir: /var/www/html
        environment:
            TZ: '${TZ:-}'
            XDEBUG_CONFIG: remote_host=host.docker.internal
        volumes:
            - .:/var/www/html
            - ./docker/local/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./docker/local/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - lv_network
        depends_on:
            - database
            - queue
            - cache
        ports:
            - "9000:9000"
            - "9003:9003"
            - "9191:9191"

    http:
        container_name: lv_http
        image: nginx:latest
        restart: always
        environment:
            TZ: '${TZ:-}'
        ports:
            - "8003:80"
        volumes:
            - ./public:/var/www/html/public
            - ./docker/local/http/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/local/http/logs:/var/log/nginx
        networks:
            - lv_network

    queue:
        container_name: lv_queue_db
        image: redis:latest
        restart: always
        environment:
            TZ: '${TZ:-}'
        volumes:
            - 'lv_queue_db:/data'
        ports:
            - "6002:6379"
        networks:
            - lv_network

    cache:
        container_name: lv_cache_db
        image: redis:latest
        restart: always
        environment:
            TZ: '${TZ:-}'
        volumes:
            - 'lv_cache_db:/data'
        ports:
            - "6003:6379"
        networks:
            - lv_network

    database:
        container_name: lv_database
        image: postgres:15
        restart: always
        environment:
            TZ: '${TZ:-}'
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-lv_database}'
            POSTGRES_USER: '${DB_USERNAME:-user}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'lv_database:/var/lib/postgresql/data'
        ports:
            - "3002:5432"
        networks:
            - lv_network

    database_testing:
        container_name: lv_database_testing
        image: postgres:15
        restart: always
        environment:
            TZ: '${TZ:-}'
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-lv_database_testing}'
            POSTGRES_USER: '${DB_USERNAME:-user}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'lv_database_testing:/var/lib/postgresql/data'
        ports:
            - "3009:5432"
        networks:
            - lv_network

networks:
    lv_network:
        driver: bridge

volumes:
    lv_database:
        driver: local
    lv_queue_db:
        driver: local
    lv_cache_db:
        driver: local
    lv_database_testing:
        driver: local
